# Generated by Django 4.1 on 2022-08-18 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="News",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("content", models.TextField(blank=True)),
                ("created_att", models.DateTimeField(auto_now_add=True)),
                ("update_att", models.DateField(auto_now=True)),
                ("photo", models.ImageField(upload_to="images/news/%Y/%m/%d/")),
                ("is_published", models.BooleanField(default=True)),
            ],
        ),
    ]
