# Generated by Django 4.1 on 2022-08-18 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("index", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(old_name="News", new_name="Index",),
    ]
